# Generated by Django 3.1.4 on 2020-12-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_foundation', models.DateTimeField(auto_now_add=True)),
                ('filial_of_university', models.CharField(blank=True, max_length=100, verbose_name='Филиал университета')),
            ],
        ),
        migrations.CreateModel(
            name='Colledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_foundation', models.DateTimeField(auto_now_add=True)),
                ('filial_of_university', models.CharField(blank=True, max_length=100, verbose_name='Филиал университета')),
            ],
        ),
        migrations.CreateModel(
            name='Gymnasium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_foundation', models.DateTimeField(auto_now_add=True)),
                ('filial_of_university', models.CharField(blank=True, max_length=100, verbose_name='Филиал университета')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_foundation', models.DateTimeField(auto_now_add=True)),
                ('filial_of_university', models.CharField(blank=True, max_length=100, verbose_name='Филиал университета')),
            ],
        ),
    ]
