# Generated by Django 3.1.4 on 2021-01-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('General_education_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_education_system',
            name='door_room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dorm_room'),
        ),
    ]
