# Generated by Django 3.1.4 on 2020-12-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('General_education_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='Dorm_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dorm_room'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='Faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.faculty'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course'),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.direction'),
        ),
    ]
