# Generated by Django 3.1.4 on 2020-12-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General_education_system', '0002_auto_20201228_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='Dorm_room',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='Faculty',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='direction',
        ),
    ]
