# Generated by Django 3.1.4 on 2020-12-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='footer_project.aboutus', verbose_name='О нас')),
                ('contacts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='footer_project.contacts', verbose_name='Контакты')),
            ],
        ),
    ]
