# Generated by Django 3.1.4 on 2020-12-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer_project', '0002_aboutcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Oportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abiturient_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footer_project.abiturienthelpinformation', verbose_name='Информация для абитуриентов')),
                ('student_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footer_project.studenthelpinformation', verbose_name='Информация для студентов')),
            ],
        ),
    ]
