# Generated by Django 3.1.4 on 2021-01-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='dorm_bulding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dorm_building'),
        ),
        migrations.AddField(
            model_name='dorm_building',
            name='dorm_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dorm_room'),
        ),
    ]
