# Generated by Django 3.1.4 on 2021-01-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210111_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm_building',
            name='dorm_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.dorm_room'),
        ),
    ]
